CREATE TABLE RESTAURANTS (
    ID 				INTEGER,
    NAME 			VARCHAR(50),
    DESCRIPTION 	VARCHAR(280),
    LOCATION 		VARCHAR(50),
    CONTACT_NAME 	VARCHAR(20),
	CONTACT_PHONE 	INTEGER,
	CREATED_AT 		TIMESTAMP,
	MODIFIED_AT 	TIMESTAMP
);

CREATE TABLE MENU_DISHES (
    ID 				INTEGER,
    NAME 			VARCHAR(50),
    DESCRIPTION 	VARCHAR(280),
    PRICE_1_HEADER 	VARCHAR(280),
	PRICE_1 		FLOAT,
	PRICE_2_HEADER 	VARCHAR(280),
	PRICE_2 		FLOAT,
	CREATED_AT 		TIMESTAMP,
	MODIFIED_AT 	TIMESTAMP
);

CREATE TABLE MENU_GROUPS (
    ID 				INTEGER,
    NAME 			VARCHAR(50),
    DESCRIPTION 	VARCHAR(280),
	CREATED_AT 		TIMESTAMP,
	MODIFIED_AT 	TIMESTAMP
);

CREATE TABLE MENUS (
    ID 				INTEGER,
    NAME			VARCHAR(50),
    DESCRIPTION		VARCHAR(280),
    RESTAURANT_ID 	INTEGER,
	GROUP_ID 		INTEGER,
	DISH_ID 		INTEGER,
	CREATED_AT 		TIMESTAMP,
	MODIFIED_AT 	TIMESTAMP
);

CREATE TABLE COMMENTS (
    ID 				INTEGER,
    USER_ID 		INTEGER,
    TITLE 			VARCHAR(50),
    CONTENT			VARCHAR(500),
	STARS 			INTEGER,
	RESTAURANT_ID 	INTEGER,
	CREATED_AT 		TIMESTAMP,
	MODIFIED_AT 	TIMESTAMP
);

CREATE TABLE RATED_COMMENTS (
    ID 				INTEGER,
    USER_ID 		INTEGER,
    COMMENT_ID 		INTEGER,
	VALUATION		BOOLEAN
);

CREATE TABLE USERS (
    ID 				INTEGER,
    NAME 			VARCHAR(20),
    USERNAME 		VARCHAR(25),
    PASSWORD 		VARCHAR(25),
	EMAIL			VARCHAR(50)
);
